### ISSUE TITLE
BOOST_USE_WINAPI_VERSION is not honored

### ISSUE THREAD

**Issue by donbcd** [retf/Boost.Application#48] opened 2015-12-28 11:56 UTC
Boost 1.60.0 has introduced BOOST_USE_WINAPI_VERSION and changed the default compilation behavior (see the Release Notes). 
This should be used for all windows-implementations!
As a positive side-effect this will also deprecate the need for the "WinSdkVerVista.h-Patch" introduced by @BurningEnlightenment in Pull Request #40, which is dangerous anyway (breaks other libs using windows-includes).

**Comment by BurningEnlightenment** [comment] 2015-12-28 14:21
Sounds reasonable, but I would go one step further and replace `#include <shlobj.h>` and all used winapi symbols by their [boostorg/winapi](https://github.com/boostorg/winapi) counterparts... I'll submit a pr.

**Comment by BurningEnlightenment** [comment] 2015-12-28 15:30
My first analysis: We need
- [x] `DWORD` in `process_id_impl.hpp` -> use `DWORD_` from `detail/winapi/basic_types.hpp`
- [x] `GetModuleFileNameW` in `path_impl.hpp` -> use `get_module_file_name` from `detail/winapi/dll.hpp`
- [x] `GetTempPathW` in `path_impl.hpp` -> use `boost::filesystem::temp_directory_path()`
- [ ] `MAX_PATH` in `path_impl.hpp`
- [ ] `ERROR_INSUFFICIENT_BUFFER` in `path_impl.hpp`
- [ ] `SHGetKnownFolderPath` and related symbols in `path_impl.hpp`
The last three symbols aren't provided by boost at the moment. We can easily work around the missing `MAX_PATH` and `ERROR_INSUFFICIENT_BUFFER` defines by providing their values as constants. We can also import SHGetKnownFolderPath and define the used GUIDs manually, but the question is: Where? In which file? In which namespace? Should we ask the boost winapi library team to provide those symbols?

**Comment by BurningEnlightenment** [comment] 2015-12-28 16:03
> "WinSdkVerVista.h-Patch" [...] which is dangerous anyway (breaks other libs using windows-includes).

@donbcd can you elaborate on this?

**Comment by donbcd** [comment] 2015-12-29 08:14
> @donbcd can you elaborate on this?

The header does not define the windows-version for the whole project, so some parts might work with different windows-sdk-versions, which breaks some libs linking.
Where I noticed this was with boost.log, which is included in many parts of the project. Different windows-versions defined would result in linking different libs. Only workaround would have been to include the WinSdkVerVista.h in every file that uses the windows sdk. Or: defining the windows version globally, as with BOOST_USE_WINAPI_VERSION.

**Comment by BurningEnlightenment** [comment] 2015-12-29 09:09
Well, it was intended that you define the windows version globally by including `WinSdkVerVista.h` in a prefix/precompiled header file :persevere:.

However, I fixed this issue with #49 and #50, so you may close this.

**Closed** 2015-12-29 09:19 UTC
Labels: bug
